### PR TITLE
spectroscopy module

### PR DESCRIPTION
**Pull request by neilzim**
## Describe your changes

- New module containing step function prototypes for spectroscopic data calibration.
- Test functions to verify the performance of prism-dispersed PSF centroids, dispersion profile fit, wavelength calibration, star spectrum registration, and line spread function fit.
- New subdirectory for spectroscopy test data inputs under tests/test_data/spectroscopy/

## Type of change

- New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [x] I have linted my code
- [x] I have verified that all unit tests pass in a clean environment and added new unit tests, as needed
- [x] I have verified that all docstrings are properly formatted and added new documentation, as needed

### CODE REVIEW

**Comment by semaphoreP** [comment]
Hi @neilzim, the code here isn't in the model of step functions and data classes that we have for the rest of corgidrp. Is that something you have time to work on? If not, we need to find someone to make that interface before we can merge this code.

We also should put the FITS files used in the tests in Git LFS, instead of being tracked via regular git.

**Comment by neilzim** [comment]
I will not have time to rework the functions + classes this fall.

**Comment by semaphoreP** [comment]
Let's not close this PR. I'm going to merge your changes into a `spectroscopy` branch and we can see if we can get some help from the rest of the DRP team to refactor the code.

**Comment by semaphoreP** [comment]
@neilzim, before I merge, can you update add the FITS files in this PR into the `.gitattributes` file in the base of the directory (following the syntax of the examples that are there (https://github.com/neilzim/corgidrp/blob/main/.gitattributes). That way, they get merged into this repo straight into git LFS. Hopefully this is quick and only takes a few minutes of your time.

**Comment by semaphoreP** [comment]
If you give me write access to your fork of the repo, I can do it myself as well.

**Comment by neilzim** [comment]
Sure, I've just modified the gitattributes to include all the test inputs.

**Comment by semaphoreP** [comment]
We need to `filter=lfs diff=lfs merge=lfs -text` appended to each line as well.

**Review by semaphoreP — APPROVED** [review]
Ok for now, additional interface dev needed.

**Pull request merged**
