### PR TITLE
Use dataset instead of single frame for guessing recipes

### PR DESCRIPTION
**Pull request by semaphoreP**
## Describe your changes

To help @hsergi with nonlinearity, since we will need to check multiple files, and not just the first file

## Type of change

Please delete options that are not relevant (and this line).

- Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review
- [x] I have linted my code
- [x] I have verified that all unit tests pass in a clean environment and added new unit tests, as needed
- [x] I have verified that all docstrings are properly formatted and added new documentation, as needed

### CODE REVIEW

**Comment by maxwellmb** [comment]
Doesn't this still just use the first frame?

**Comment by semaphoreP** [comment]
You now have the option to use the whole dataset.

**Comment by maxwellmb** [comment]
Ah, I see. So the purpose of this change is to enable future developers (Sergi soon) to write their own `guess_template` logic with the whole `dataset`?

**Comment by semaphoreP** [comment]
Yep

**Review by maxwellmb — APPROVED** [review]

**Pull request merged**
