### PR TITLE
Update installation and enable toggling of errors

### PR DESCRIPTION
**Pull request by semaphoreP**
corgidrp config file and caldb now save to `~/.corgidrp` folder by default

New setting to enable whether individual error terms are saved or not. By default, this is set to false. 

Hopefully this didn't break anything (waiting on tests)

### CODE REVIEW

**Comment by semaphoreP** [comment]
actually this will certainly cause tests to fail. will need to change behaviors of tests before this can be merged

**Review by maxwellmb — COMMENTED** [review]
I think that with the introduction of the config file, we should briefly write down (for other developers) its purpose so that people know when to use it and when not to use it (e.g. when the constants.py file is more appropriate). 

Otherwise this looks good to me. 

I think we should merge #63 into main first and then have you merge that here.

**Comment by maxwellmb** [comment]
The other thing that just occurred to me: For reproducibility we may want to write the config file (or at least certain keywords) to fits headers.

**Comment by JuergenSchreiber** [comment]
I agree with @maxwellmb. Documentation is essential. Good thing is to track the errors in the HISTORY header.

**Comment by semaphoreP** [comment]
Ok I fixed the tests that were failing, added a keyword in the error HDU to indicate if we're tracking individual errors, and added to the README on when to use it. @maxwellmb can you look over again, and approve if it looks good?

**Review by maxwellmb — APPROVED** [review]
Ok, I think this overall looks good to me!

**Pull request merged**
