### PR TITLE
Port L1 to L2 data analysis code from iit 

### PR DESCRIPTION
**Pull request by mygouf**
Ported L1 to L2 data analysis code from iit.
Updated the example script ttr5_analog.py accordingly to match the analysis code architecture. 
Provided comments and suggestions directly into the ttr5_analog.py script. 
Added new classes for each processing level with a complete description of those data levels in the documentation.
This pull request is relevant to issues #12 and #13 but don't address them completely. More work is needed to do to fully port the code. Once this is reviewed and merged I'll create relevant issues to facilitate and coordinate the implementation.

### CODE REVIEW

**Comment by mygouf** [comment]
> Hi Marie, I think we shouldn't merge this code into `main` until we spend more time porting the code over. In particular, we aren't using the same class architecture as the II&T pipeline.
> 
> Instead, I suggest we port functionality one at a time over, rather than copying all the code and modifying it later.

Sure, I wasn't sure how you wanted to proceed. I'm good with waiting for a more complete implementation before merging.

**Comment by mygouf** [comment]
> I think the changes to ttr5_analog.py should wait as well as. This was meant to be more of a guiding script for new people doing corgidrp development to give everyone an idea about general architecture philosophy (function-based rather than too class-heavy) rather than actually be how things would be run.

I had initially started a separate script with those new edits but I was not comfortable about having separate versions of it once we move forward with the porting of L1 to L2 data analysis.

> The "Options" you suggested are excellent and I think are further ahead than this example was meant to be. How exactly we package things to run L1-L2a together is still something to be discussed, but we will definitely do that at some point both for convenience and for testing.

I'd be in favor to discuss this early on as this will facilitate future development and testing. 

> When we break out functions into issues, we should make sure to make note on the github issues on the very useful pointers you've made in tt5_analog.py to similar functions in the II&T pipeline!

Yes, this is planned! I'll go ahead and create the issues then as soon as I have some time.

**Comment by semaphoreP** [comment]
I just sent an email to have a meeting to discuss how the broader data reduction framework will look like. Regardless, I believe compartmentalizing the steps into the functional framework outlined for corgidrp should work. The question is just want code will live on top of it that strings together the pipeline steps.

**Comment by maxwellmb** [comment]
Closing this old pull request back from the early days.

**Pull request closed without merging**
